# Generated by Django 5.0.6 on 2024-07-18 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('cod_comic', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=400)),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(upload_to='comics')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas_sharingann.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=15)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas_sharingann.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('f_venta', models.DateField()),
                ('f_despacho', models.DateField()),
                ('f_entrega', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.BooleanField(verbose_name='¿El usuario tiene objetos en el carrito?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas_sharingann.usuario')),
            ],
        ),
    ]
